services:
  taskhub.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Api__BaseAddress=http://taskhub.api:8080
      - DemoAuth__Username=${TASKHUB_DEMO_USERNAME}
      - DemoAuth__Password=${TASKHUB_DEMO_PASSWORD}
      - TaskHub__Links__SwaggerUrl=http://localhost:8080/swagger/index.html
    depends_on:
      taskhub.api:
        condition: service_started
      db:
        condition: service_healthy
    ports:
      - "5262:8080"

  taskhub.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__TaskHub=Server=db,1433;Database=TaskHub;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True
      - Jwt__Issuer=${TASKHUB_JWT_ISSUER}
      - Jwt__Audience=${TASKHUB_JWT_AUDIENCE}
      - Jwt__SigningKey=${TASKHUB_JWT_SIGNING_KEY}
      - DemoAuth__Username=${TASKHUB_DEMO_USERNAME}
      - DemoAuth__Password=${TASKHUB_DEMO_PASSWORD}
    ports:
      - "8080:8080"

  db:
    ports:
      - "1433:1433"
