services:
  taskhub.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__TaskHub=Server=db,1433;Database=TaskHub;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${USER_SECRETS_PATH}:/home/app/.microsoft/usersecrets:ro
      - ${USER_SECRETS_PATH}:/root/.microsoft/usersecrets:ro
      - ${HTTPS_CERTS_PATH}:/home/app/.aspnet/https:ro
      - ${HTTPS_CERTS_PATH}:/root/.aspnet/https:ro
